run:
  modules-download-mode: readonly # Do not update dependencies.
  concurrency: 4
  timeout: 3m
linters-settings:
  varnamelen:
    min-name-length: 2
linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - typecheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard # ? is not allowed from list 'Main' - maybe bug. Check later
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
#    - execinquery # Deprecated.
    - exhaustive
    # - exhaustruct
    # - exportloopref // The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant.
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - intrange
#    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    # - nolintlint # Let's keed nolintlint if we decide to add it.
    # - nonamedreturns # This linter does not make any sense.
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
    - gosmopolitan
    - mirror
    - tagalign
    - testifylint
    - sloglint
    - spancheck
    - protogetter
    - perfsprint
    - gochecksumtype
issues:
    exclude-rules:
      - path: _test\.go
        linters:
          - dupl
          - funlen
          - dupword
      - path: doc\.go
        linters:
          - lll
      - path: constraints\/constraints_test\.go
        linters:
          - gocritic
          - wsl
          - gochecknoglobals
          - varnamelen
          - gosec
          - cyclop
          - unconvert
          - paralleltest
          - tparallel
          - unused
