# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml.
run:
  modules-download-mode: readonly # Do not update dependencies.
linters-settings:
  gomnd:
    ignored-numbers:
      - "0"
      - "0.0"
      - "1"
      - "1.0"
      - "2"
      - "2.0"
  varnamelen:
    min-name-length: 2
  gomoddirectives:
    retract-allow-no-explanation: true # Allow during some issue.
linters:
  disable-all: true
  enable:
    # Default linters
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Additional linters
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - golint # Deprecated.
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - ifshort
    - importas
    # - interfacer # Deprecated.
    # - ireturn # This linter does not work well with generics.
    - lll
    - maintidx
    - makezero
    # - maligned # Deprecated.
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    # - nolintlint # Let's keed nolintlint if we decide to add it.
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    # - scopelint # Deprecated.
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    # - thelper # It's useless linter for now.
    - tparallel
    - unconvert
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    # - nonamedreturns # This linter does not make any sense.
    - nosprintfhostport
issues:
    exclude-rules:
      - path: _test\.go
        linters:
          - cyclop
          - funlen
          - dupl
          - gocognit
          - goconst
          - gocyclo
          - lll
      - path: doc\.go
        linters:
          - lll
      - linters:
        - paralleltest
        text: "does not use range value in test Run"
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.45.x # use the fixed version to not introduce new linters unexpectedly
