version: '3'

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test ./...
    env:
      GOFLAGS: -count=1
  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...
  lint:fix:
    desc: Run linter and fix issues
    cmds:
      - golangci-lint run --fix ./...
  verify:
    desc: Run linter and unit tests together
    deps:
      - test
      - lint
